# Generated by Django 2.2.24 on 2021-08-01 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0040_viewrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewrecord',
            options={'verbose_name': '访问记录', 'verbose_name_plural': '访问记录'},
        ),
    ]
